---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ./answerfile.yml
  tasks:
    - name: NSX-T Logical Switch
      nsxt_logical_switch:
        display_name: "{{ hostvars['localhost'].ls_name }}"
        description: "Management Logical Switch"
        transport_zone_id: "{{ overlay_tzone.id }}"
        tags:
          ncp/cluster: "{{ hostvars['localhost'].tag }}"
        state: present
        nsx_manager: "{{ hostvars['nsx-manager'].ansible_ssh_host }}"
        nsx_username: 'admin'
        nsx_passwd: "{{ hostvars['nsx-manager'].ansible_ssh_pass }}"
      register: lsswitch

    - name: NSX-T Logical Switch Port
      nsxt_logical_switch_port:
        display_name: "LSPort"
        description: "Logical Switch Port"
        logical_switch_id: "{{ lsswitch.id }}"
        tags:
          ncp/cluster: "{{ hostvars['localhost'].tag }}"
        state: present
        nsx_manager: "{{ hostvars['nsx-manager'].ansible_ssh_host }}"
        nsx_username: 'admin'
        nsx_passwd: "{{ hostvars['nsx-manager'].ansible_ssh_pass }}"
      register: lsp

    - name: NSX-T Logical Router Downlink Port
      nsxt_logical_router_downlink_port:
        display_name: "DwnPort"
        description: "Logical Router Downlink Port"
        logical_router_id: "{{ t1.id }}"
        linked_logical_switch_port_id: "{{ lsp.id }}"
        subnets:
           - ip_addresses: "{{ hostvars['localhost'].t1_ip }}"
             prefix_length: "{{ hostvars['localhost'].t1_mask }}"
        tags:
          ncp/cluster: "{{ hostvars['localhost'].tag }}"
        state: present
        nsx_manager: "{{ hostvars['nsx-manager'].ansible_ssh_host }}"
        nsx_username: 'admin'
        nsx_passwd: "{{ hostvars['nsx-manager'].ansible_ssh_pass }}"
      register: lrdp



