---
- name: Deploy NSX-T Edge Gw OVA
  hosts: localhost
  gather_facts: False
  tasks:
    - name: deploy NSX Edge Gw OVA using default vCenter
      deploy_ova:
        ovftool_path: "{{ hostvars['localhost'].ovfToolPath }}"
        datacenter: "{{ hostvars[item]['dc'] }}"
        datastore: "{{ hostvars[item]['datastore'] }}"
        portgroup: "{{ hostvars[item]['portgroup'] }}"
        portgroup_ext: "{{ hostvars[item]['portgroupExt'] }}"
        portgroup_transport: "{{ hostvars[item]['portgroupTransport'] }}"
        cluster: "{{ hostvars[item]['cluster'] }}"
        vmname: "{{ hostvars[item]['vmname'] }}"
        hostname: "{{ hostvars[item]['hostname'] }}"
        dns_server: "{{ hostvars['localhost'].dns_server }}"
        dns_domain: "{{ hostvars['localhost'].dns_domain }}"
        ntp_server: "{{ hostvars['localhost'].ntp_server }}"
        gateway: "{{ hostvars[item]['gw'] }}"
        ip_address: "{{ hostvars[item].ansible_ssh_host }}"
        netmask: "{{ hostvars[item]['mask'] }}"
        admin_password: "{{ hostvars[item].ansible_ssh_pass }}"
        cli_password: "{{ hostvars[item].ansible_ssh_pass }}"
        ssh_enabled: "{{ hostvars['localhost'].sshEnabled }}"
        allow_ssh_root_login: "{{ hostvars['localhost'].allowSSHRootAccess }}"
        path_to_ova: "{{ hostvars['localhost'].nsxOvaPath }}"
        ova_file: "{{ hostvars['localhost'].edgeOva }}"
        vcenter: "{{ hostvars['localhost'].deployVcIPAddress }}"
        vcenter_user: "{{ hostvars['localhost'].deployVcUser }}"
        vcenter_passwd: "{{ hostvars['localhost'].deployVcPassword }}"
        deployment_size: "{{ hostvars['localhost'].nsx_t_edge_deploy_size }}"
      with_items: "{{ groups['nsxedges'] }}"
      async: 7200
      poll: 0
      when: hostvars['localhost'].edge_vcenter_host is not defined or hostvars['localhost'].edge_vcenter_host == '' or hostvars['localhost'].edge_vcenter_host == 'null'
      register: deploy_nsx_edges
    - name: deploy NSX Edge Gw OVA using separate Edge vCenter
      deploy_ova:
        ovftool_path: "{{ hostvars['localhost'].ovfToolPath }}"
        datacenter: "{{ hostvars[item]['edge_dc'] }}"
        datastore: "{{ hostvars[item]['edge_datastore'] }}"
        portgroup: "{{ hostvars[item]['edge_portgroup'] }}"
        portgroup_ext: "{{ hostvars[item]['portgroupExt'] }}"
        portgroup_transport: "{{ hostvars[item]['portgroupTransport'] }}"
        cluster: "{{ hostvars[item]['edge_vcenter_cluster'] }}"
        vmname: "{{ hostvars[item]['vmname'] }}"
        hostname: "{{ hostvars[item]['hostname'] }}"
        dns_server: "{{ hostvars['localhost'].edge_dns_server }}"
        dns_domain: "{{ hostvars['localhost'].edge_dns_domain }}"
        ntp_server: "{{ hostvars['localhost'].edge_ntp_server }}"
        gateway: "{{ hostvars[item]['edge_gw'] }}"
        ip_address: "{{ hostvars[item].ansible_ssh_host }}"
        netmask: "{{ hostvars[item]['edge_mask'] }}"
        admin_password: "{{ hostvars[item].ansible_ssh_pass }}"
        cli_password: "{{ hostvars[item].ansible_ssh_pass }}"
        ssh_enabled: "{{ hostvars['localhost'].sshEnabled }}"
        allow_ssh_root_login: "{{ hostvars['localhost'].allowSSHRootAccess }}"
        path_to_ova: "{{ hostvars['localhost'].nsxOvaPath }}"
        ova_file: "{{ hostvars['localhost'].edgeOva }}"
        vcenter: "{{ hostvars['localhost'].edge_vcenter_host }}"
        vcenter_user: "{{ hostvars['localhost'].edge_vcenter_user }}"
        vcenter_passwd: "{{ hostvars['localhost'].edge_vcenter_password }}"
        deployment_size: "{{ hostvars['localhost'].nsx_t_edge_deploy_size }}"
      with_items: "{{ groups['nsxedges'] }}"
      async: 7200
      poll: 0
      when: hostvars['localhost'].edge_vcenter_host is defined and hostvars['localhost'].edge_vcenter_host != '' and hostvars['localhost'].edge_vcenter_host != 'null'
      register: deploy_nsx_edges
    - name: Wait 10 minutes before starting to verify the deployment
      pause: minutes=10
    - name: Check if NSX Edges deployment has finished
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      with_items: "{{ deploy_nsx_edges.results }}"
      retries: 100
