---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: NSX-T Edge Cluster
      nsxt_edge_cluster:
        display_name: "Test Cluster"
        description: "My Test Edge Cluster"
        members:
          - Edge1
        tags:
          project: demo2
          ncp/cluster: k8s-cluster1
        state: present
        nsx_manager: "10.29.12.209"
        nsx_username: "admin"
        nsx_passwd: 'VMware1!'
      register: edge_cluster
  tags: edge_cluster
