---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: NSX-T Logical Switch Port
      nsxt_logical_switch_port:
        display_name: "testLSPort"
        description: "My Test Logical Switch Port"
        logical_switch_id: "69622bfa-5af8-429c-b769-e0400c5fefd0"
        tags:
          project: demo
          ncp/cluster: k8s-cluster1
        state: present
        nsx_manager: "10.29.12.209"
        nsx_username: "admin"
        nsx_passwd: 'VMware1!'
      register: lsp
  tags: lsp
